-- =============================================================================
-- 004 — Storage buckets: flip `documents` to private, add `portfolios`
--
-- Migration 003 created `documents` as a public bucket with permissive
-- read/insert policies on storage.objects. We now:
--   • Flip `documents` to private — uploads stay accessible only via
--     signed URLs (generated by src/lib/storage.js).
--   • Add the `portfolios` bucket (private) for student project artifacts.
--   • Replace the old open policies with a pair that covers both buckets
--     and still allows uploads from anon callers (PublicEnrollment /inscription
--     is anonymous). Tighten further in the RLS pass.
-- =============================================================================

-- 1. Existing bucket → private.
update storage.buckets
set    public = false
where  id = 'documents';

-- 2. New bucket for portfolio artifacts.
insert into storage.buckets (id, name, public)
values ('portfolios', 'portfolios', false)
on conflict (id) do nothing;

-- 3. Replace the bucket-specific policies from 003 with broader ones that
--    cover both buckets.
drop policy if exists "documents read"   on storage.objects;
drop policy if exists "documents insert" on storage.objects;

create policy "uploads read"
  on storage.objects for select
  using (bucket_id in ('documents', 'portfolios'));

create policy "uploads insert"
  on storage.objects for insert
  with check (bucket_id in ('documents', 'portfolios'));
