'use client';
import { programmeLabel } from '@/lib/ui/presentation.mjs';
import { STATUS, TASKS, LOST, NOT_QUALIFIED, dateLabel, scheduledLabel, staffLabel } from '@/lib/crm/presentation.mjs';
import { LifecycleBadge, ReadState } from './CrmShared';
import OpportunityCard, { OpportunityActions } from './OpportunityCard';
export default function OpportunitiesList({ query, stage, onOpen, onAction, filtered, onReset, staffRows }) {
  const page = query.data?.pages?.[stage || 'list'];
  return <ReadState query={query} available={Number.isFinite(query.data?.total) && Array.isArray(page?.rows)} filtered={filtered} onReset={onReset} empty={filtered ? "Aucun prospect correspondant à cette vue et ces filtres." : "Aucun prospect enregistré. Ajoutez un prospect pour commencer le suivi."}>{Array.isArray(page?.rows) && page.rows.length ? <><div className="space-y-3 md:hidden">{page?.rows.map(lead => <div key={lead.id}><p className="mb-1 text-xs font-medium text-slate-500">{STATUS[lead.status]}</p><OpportunityCard lead={lead} onOpen={onOpen} onAction={onAction} asOf={query.data?.as_of} staffRows={staffRows} /></div>)}</div>
    <div className="hidden max-w-full overflow-x-auto rounded-lg border bg-white md:block"><table className="w-full text-left text-sm"><thead className="border-b bg-slate-50 text-slate-500"><tr>{['Contact / apprenant','Étape','Responsable','Origine','Prochaine action','Dernière activité','Actions'].map(label => <th scope="col" className="p-3 font-medium" key={label}>{label}</th>)}</tr></thead><tbody>{page?.rows.map(lead => <tr key={lead.id} data-testid="opportunity-row" className="border-b last:border-0"><td className="max-w-64 p-3"><button className="min-h-9 break-words text-left focus-visible:outline-blue-600" onClick={() => onOpen(lead.id)}><span className="block font-semibold text-slate-900">{lead.contact_name}</span><span className="mt-1 block operational-secondary">{lead.learner_name || 'Apprenant à préciser'}{lead.learner_age != null ? ` · ${lead.learner_age} ans` : ''} · {programmeLabel(lead.program)}</span></button></td><td className="p-3"><LifecycleBadge status={lead.status}/>{lead.closed_at && <p className="mt-1 text-slate-500">{LOST[lead.closure_reason] || NOT_QUALIFIED[lead.closure_reason]} · {dateLabel(lead.closed_at)}</p>}</td><td className="max-w-40 break-words p-3">{lead.owner_id ? staffLabel(staffRows?.find(p=>p.id===lead.owner_id)) : 'Non attribué'}</td><td className="max-w-40 break-words p-3">{lead.source_label}</td><td className="p-3">{lead.next_task ? `${TASKS[lead.next_task.task_type]} · ${scheduledLabel(lead.next_task)}` : lead.next_placement ? `Test · ${scheduledLabel(lead.next_placement)}` : 'Aucune action'}{lead.failed_attempts > 0 && <p className="mt-1 text-slate-500">{lead.failed_attempts} appels infructueux{lead.failed_attempts >= 5 ? ' · Séquence automatique terminée' : ' sur 5'}</p>}</td><td className="p-3">{lead.last_activity_at ? dateLabel(lead.last_activity_at) : '—'}</td><td className="p-3"><OpportunityActions lead={lead} onAction={onAction} /></td></tr>)}</tbody></table></div>
    </> : null}</ReadState>;
}
